### PR TITLE
Add custom style to notification

### PR DESCRIPTION
**Pull request by tbrkollar**

### CODE REVIEW

**Comment by jingteng25742** [comment]
@tbrkollar 
I just tested out your change. 
The adding / removing of the UC component window looks good. 

The `Required SLC Component not installed` window still look the same and requires some theme / spacing update.

**Review by paulr34 — APPROVED** [review]

**Comment by tbrkollar** [comment]
I modified the all notifies. Is this window a notify or a popup window? I searched and i think it is a popup window which is in ZCLDomainClusterView.vue file.  In that case i have to create a new popup style.

**Comment by tbrkollar** [comment]
i ve already modified popup, please test it.
@jingteng25742 @paulr34

**Comment by tbrkollar** [comment]
rebase

**Comment by paulr34** [comment]
tested, looks amazing. Rebasing and merging. Nice work @tbrkollar !

**Comment by jingteng25742** [comment]
@tbrkollar 
I'm seeing the following currently. 
The color looks great but the spacing looks quite strange.
The "OTA Bootload.." is actually a list of items. 
Making the list more indented / spaced better would be nice. 
@tbrkollar I can show you how to reproduce the UI in Studio if testing is an issue.

Screenshot 2023-09-19 at 10 52 16 PM

**Comment by tbrkollar** [comment]
thanks, im working on it.

**Pull request merged**
