### PR TITLE
Resolving UI Issues

### PR DESCRIPTION
**Pull request by Amirreza-Ghasemkhani**
https://github.com/project-chip/zap/issues/556
https://github.com/project-chip/zap/issues/570 
https://github.com/project-chip/zap/issues/557
https://github.com/project-chip/zap/issues/553
https://github.com/project-chip/zap/issues/532
https://github.com/project-chip/zap/issues/527

- Update check_summary tests based on the new UI

### CODE REVIEW

**Comment by brdandu** [comment]
test/ui.test.js is failing. Can we fix that before I start looking into this?

**Comment by brdandu** [comment]
I am seeing the following in the UI which does not seem right:
Issue 1

**Comment by brdandu** [comment]
How can I verify issue 570?

**Comment by brdandu** [comment]
Still see this separation in the UI from 557
Issue 2

**Comment by brdandu** [comment]
Issue 553 seems seems to have another issue now where the count is not correct
Issue 3
 Make sure to add a test for this once it is fixed

**Comment by brdandu** [comment]
Issue 532 still seems to be the case. I go to cluster config or preferences and come back but see the preview pane still showing up.

**Review by brdandu — CHANGES_REQUESTED** [review]
Take a look at all the comments

**Comment by Amirreza-Ghasemkhani** [comment]
I will take a look at the issue that you mentioned.

**Comment by Amirreza-Ghasemkhani** [comment]
> I am seeing the following in the UI which does not seem right: Issue 1
> 
> Just do Cluster configurator: Zigbee/Matter like @tecimovic suggested
> 
> Also I do not see a logo which was suggested by @jingteng25742

logo or Icon? because I added icon for smaller viewpoints if you resize the page you will see it will convert to just a icon ...
image

**Comment by Amirreza-Ghasemkhani** [comment]
> Still see this separation in the UI from 557 Issue 2

which one do you perfer? 
1. 
image
2.
image
3.
image

**Comment by brdandu** [comment]
> > Still see this separation in the UI from 557 Issue 2
> 
> which one do you perfer? 1. image 2. image 3. image

I am fine with 3 but why do we have a shadow from the top on the right side but not the left? not a big deal but if you can remove that to make it look the same on both sides then great. If not lets just go with 3.

**Comment by Amirreza-Ghasemkhani** [comment]
> > > Still see this separation in the UI from 557 Issue 2
> > 
> > 
> > which one do you perfer? 1. image 2. image 3. image
> 
> I am fine with 3 but why do we have a shadow from the top on the right side but not the left? not a big deal but if you can remove that to make it look the same on both sides then great. If not lets just go with 3.

@brdanduIt’s because I took the screenshot when inspection elements were open, it’s okay without of any extra shadows if you don't open the inspect part of the site
.

**Comment by brdandu** [comment]
> I am seeing the following in the UI which does not seem right: Issue 1
> 
> Just do Cluster configurator: Zigbee/Matter like @tecimovic suggested
> 
> Also I do not see a logo which was suggested by @jingteng25742

2 things here:
1) Get rid of the display button text
2) The "Cluster Configurator" text is getting cached which we do not want. When I switch between SDKs this does not get updated automatically

**Comment by brdandu** [comment]
I switched between "npm run zap" and launching zap using the Zigbee stack and I still see the following:
Screen Shot 2022-08-10 at 9 27 07 AM

@Amirreza-Ghasemkhani as per our conversation, this should be updated based on the stack we are using. This way it just shows whatever got picked up first

**Review by brdandu — APPROVED** [review]
Feel free to merge and then fix the Cluster Configurator Issue

**Pull request merged**
