### PR TITLE
Rename CLI executable to zap-cli and point apack.json to it

### PR DESCRIPTION
**Pull request by tecimovic**

### CODE REVIEW

**Comment by jingteng25742** [comment]
Have we tested the CLI exe through all the CI already?

**Comment by tecimovic** [comment]
I tested it locally and it worked ok. Our internal build engineers, are ok with merging this in, and then taking a new release and testing it. It's simpler than wrangling with changing the CI to point to the PR and so on.

And Matter, at this point, is unaffected by this at all, as it doesn't use apack.json.

**Review by jingteng25742 — DISMISSED** [review]
zap-cli broken.

**Comment by tecimovic** [comment]
The /snapshot should be fixed now, so we should be good to go.

**Comment by jingteng25742** [comment]
Tested via Studio rel b1748. Sample app generation with Z3Light / Z3Switch are working.

**Pull request merged**
