### PR TITLE
Remove temp state because uc_upgrade now works on Studio without tempstate

### PR DESCRIPTION
**Pull request by brdandu**
JIRA: ZAPP-1362

### CODE REVIEW

**Comment by paulr34** [comment]
Ive been testing this and it appears to be working well. Leaning towards approving but am going to run through some more use cases to make sure.

**Review by paulr34 — APPROVED** [review]
Approved

**Review by tecimovic — COMMENTED** [review]
Paul was not wrong we need to test this well, but in general it's a right thing.

**Comment by brdandu** [comment]
> Paul was not wrong we need to test this well, but in general it's a right thing.

I have tested this for matter and zigbee apps. Went through the matter application upgrade process with Michael Rupp from the matter team as well showing how it passes now.

**Review by ethanzhouyc — APPROVED** [review]

**Review by paulr34 — CHANGES_REQUESTED** [review]
I would like @tecimovic to approve before merge

**Comment by paulr34** [comment]
@tecimovic @brdandu 

we need testing for this change or else any change after is a risk, right?

**Review by tecimovic — APPROVED** [review]
Right thing to do, the question is have we done enough testing. But I assume we did, so I'm ok with this.

**Review by paulr34 — APPROVED** [review]

**Pull request merged**
